# -*- coding: utf-8 -*-
"""
Created on Mon May  8 16:21:19 2023

@author: meimei
"""
import pandas as pd
import numpy as np
import openpyxl
import os
from SourceCode.utils import temporary_storage
from SourceCode.utils import resolve_hyphen, resolve_comma, resolve_all
from scipy.sparse import csr_matrix
from alive_progress import alive_bar
from concurrent import futures
from tqdm import tqdm
from SourceCode.utils import logging
from SourceCode.utils import MRIO_df_to_vec, MRIO_vec_to_df
from SourceCode.exog_vars import exog_vars

class scenario:
    """
    A policy scenario including the following elements:
    * Carbon tax
    * CBAM
    * Final demand
    * Investment by
    * Investment converter (adjustment)
    * Supply constraints (adjustment)
    * Price change
    * Input-output coefficients (adjustment)

    Attributes
    ------
    EXOG_VARS : exog_vars
        exog_vars object containing exogenous variables

    scenario_path : str
        path to the scenario file

    Log : logging
        logging object used for writing logs

    Methods
    -------

    set_carbon_tax
        Reads out carbon tax specification from the scenario file and constructs the necessary
        long-form matrix of tax incidences. Note: the function uses a parallelized approach
        and local storage (temporary storage) when construction the matrices due to the size
        of the necessary matrices.

    carbon_tax_rate_loop(country:str)
        works together with `set_carbon_tax`, it is the internal parallel loop function for
        calculating carbon tax matrices in a parallel manner for each of the countries specified
        in the policy scenario

    set_tax_rate(carbon_tax_incidence:pd.DataFrame)
        sets the actual tax rate based on the carbon tax incidence calculated from carbon taxes



    """
    def __init__(self, EXOG_VARS:exog_vars, scenario_path:str, Log:logging):
        self.scenario_file = scenario_path
        self.scenario_data = openpyxl.load_workbook(scenario_path, read_only=True)
        # self.name = scenario_name

        self.REGIONS = EXOG_VARS.R
        self.PRODUCTS = EXOG_VARS.P
        self.IND_BASE = EXOG_VARS.IND_BASE.reset_index()

        self.HH_BASE = EXOG_VARS.HH_BASE # type: ignore
        self.GOV_BASE = EXOG_VARS.GOV_BASE # type: ignore
        self.FCF_BASE = EXOG_VARS.FCF_BASE # type: ignore

        self.regions_length = self.REGIONS.shape[0]
        self.products_length = self.PRODUCTS.shape[0]

        self.temp = temporary_storage("Temp")
        self.tax_rate = pd.DataFrame()

        self.Log = Log

        # initialize scenario values

        self.set_fd_exog()

    def set_carbon_tax(self):
        # first we read in the scenario file, the columns are set in the template
        try:
            tax_rate = pd.read_excel(self.scenario_file, sheet_name="Carbon tax", skiprows=14)
            tax_rate = tax_rate[['Country ISO*','Emitting sectors covered*','Fuel sectors covered*',
                                 'Tax value (USD / tCO2)*']]
            tax_rate.columns = ['REG_imp','PROD_COMM','TRAD_COMM','delta_tax']
            # TODO type is deprecated 
            tax_rate['type'] = 'carbon'

        except ValueError:
            # catch if there is no sheet
            # TODO type is deprecated 
            tax_rate = pd.DataFrame(columns=['REG_imp','PROD_COMM','TRAD_COMM','delta_tax','type'])

        # setting up for parallel processing
        self.tax_rate = tax_rate
        
        print("Generating carbon tax files... Parallel started.")
        # tax rate files are generated by REG_imp country
        with futures.ThreadPoolExecutor() as executor:
            results = list(tqdm(executor.map(self.carbon_tax_rate_loop, tax_rate['REG_imp'].unique()), 
                      total=len(tax_rate['REG_imp'].unique())))
            
        del results

        self.carbon_tax_countries = list(tax_rate['REG_imp'].unique())

        return True


    def carbon_tax_rate_loop(self, country:str):
        """Parallel loop function for generating tax matrices by country. Saves the tax rate
        matrices in file.

        Parameters
        ----------
        country : str
            country to generate carbon tax file for

        Returns
        -------
        bool
            Returns True if completed
        """
          
        # first retrieve the tax rate file from the class
        tax_rate = self.tax_rate

        # TODO REG_exp is ALL for now
        tax_rate['REG_exp'] = 'ALL'
        tax_rate_country = tax_rate[tax_rate['REG_imp']==country].copy()

        # process flows_table, for simplicity the flows table (excel) allows flows to
        # be allocated to multiple sectors either in hyphen e.g. 10-30 or comma e.g.
        # 10,11,15 format, these are parsed to actual sectors here

        tax_rate_country = resolve_hyphen(tax_rate_country, 'PROD_COMM')
        tax_rate_country = resolve_comma(tax_rate_country, 'PROD_COMM')
        tax_rate_country = resolve_hyphen(tax_rate_country, 'TRAD_COMM')
        tax_rate_country = resolve_comma(tax_rate_country, 'TRAD_COMM')

        tax_rate_country = resolve_comma(tax_rate_country, 'REG_imp')

        # treatment of ALL in PROD_COMM, ie all upstream sectors impacted
        # ! FD_2 to FD_6 is missing!!!!!
        tax_rate_country = resolve_all(tax_rate_country, 'PROD_COMM', [x for x in np.arange(1,121)] + ['FD_1'])
        tax_rate_country = resolve_all(tax_rate_country, 'TRAD_COMM', [x for x in np.arange(1,121)])
        tax_rate_country = resolve_all(tax_rate_country, 'REG_exp', self.REGIONS['Region_acronyms'].to_list())
        tax_rate_country = resolve_all(tax_rate_country, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())

        tax_rate_country = tax_rate_country.rename(columns={'delta_tax':'ctax'})
        self.temp.save_to_pickle(tax_rate_country, "{}_carbon_tax_rate".format(country))

        return True
    
    def set_tax_rate(self, carbon_tax_incidence):
        # TODO: deprecated
        try:
            tax_rate = pd.read_excel(self.scenario_file, sheet_name="tax_scenarios")
        except ValueError:
            # catch if there is no sheet
            tax_rate = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','delta_tax','type'])

        # TODO: deprecated
        tax_rate = tax_rate[tax_rate['type']=='simple'].drop(columns=['type'])

        tax_rate = pd.concat([tax_rate, carbon_tax_incidence])
        # ! RN it only gets values from carbon tax incidence
        # ! therefore there is no parsing necessary bc that is already
        # ! parsed data

        # aggregate if there are multiple taxes, this generally should
        # NOT be the case, report duplicates first
        self.Log.log_to_csv("duplicated_taxes", tax_rate[tax_rate.duplicated(keep=False, subset=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])])
        tax_rate = tax_rate.groupby(['REG_imp','PROD_COMM','TRAD_COMM','REG_exp']).agg({'delta_tax':'sum'}).reset_index()

        tax_rate_hh = tax_rate[tax_rate["PROD_COMM"].str.contains("FD_")]
        # ! THIS IS SO WRONG (no-weighting)
        self.Log.log_to_csv("duplicated_hh_taxes", tax_rate_hh[tax_rate_hh.duplicated(keep=False, subset=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])])
        tax_rate_hh = tax_rate_hh.groupby(['REG_imp','PROD_COMM','TRAD_COMM','REG_exp']).agg({'delta_tax':'sum'}).reset_index()
        tax_rate_hh = tax_rate_hh.rename(columns={"delta_tax":"delta_tax_hh"})
        
        self.tax_rate_hh = tax_rate_hh

        tax_rate = tax_rate[~tax_rate["PROD_COMM"].str.contains('FD_')]
        tax_rate = tax_rate.set_index(["REG_imp","PROD_COMM","TRAD_COMM","REG_exp"])

        self.tax_rate = tax_rate

        return True
    
    # ^ ------------------------------------
    # ^       CBAM SHOULD COME HERE         
    # ^ ------------------------------------

    # ^ ------------------------------------
    # ^   Sheet: Final demand               
    # ^ ------------------------------------

    def set_fd_exog(self):
        # columns to be passed on
        columns_ = ['REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type']

        try:
            fd_exog = pd.read_excel(self.scenario_file, sheet_name='Final demand', skiprows=14)
            fd_exog = fd_exog[['Producing country ISO*','Consuming country ISO*','Product code*',
                                 'FD code*','Value*','Type*']]
            fd_exog.columns = columns_
        except (ValueError, KeyError):
            fd_exog = pd.DataFrame(columns=columns_)

        # add index before resolving
        fd_exog['Line'] = np.arange(len(fd_exog)).tolist()

        fd_exog = resolve_comma(fd_exog, "REG_imp")
        fd_exog = resolve_all(fd_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        fd_exog = resolve_comma(fd_exog, "REG_exp")
        fd_exog = resolve_all(fd_exog, "REG_exp", self.REGIONS['Region_acronyms'].to_list())

        fd_exog = resolve_comma(fd_exog, "TRAD_COMM")
        fd_exog = resolve_hyphen(fd_exog, "TRAD_COMM")
        fd_exog = resolve_all(fd_exog, "TRAD_COMM", [str(x) for x in np.arange(1,121)])

        fd_exog = resolve_comma(fd_exog, "PROD_COMM")
        fd_exog = resolve_all(fd_exog, "PROD_COMM", ['FD_1','FD_3','FD_4'])

        # ? Scenario.fd_exog structure is the following:
        # ? REG_imp | TRAD_COMM | PROD_COMM | Value | Type
        # ? such as PROD_COMM can only by FD_1, FD_2 ... FD_06
        # ? Type can be: abs-b [absolute-proportional-base] | abs [absolute-proportional-new] 
        # ? | rel [relative] | rel-b [relative to baseline]
        # ? if absolute is used with multiple sectors / countries
        # ? then numbers are proportionally spread out
        # ? proportionality is either to the base [abs-b] or to the current FD vector [abs]
        # TODO: abs is to be implemented later [with annualized model version]
        # TODO: rel is to be implemented later [with annualized model version]

        # WE CALCULATE FD_EXOG types here, bc the scenario class
        # should have direct impacts

        # ! INV is missing [FD_5 - FD_6]
        # ! NPISH is missing [FD_2]

        fd_01_initial = self.HH_BASE.reset_index().rename(columns={'VIPA':'FD_1'})
        fd_03_initial = self.GOV_BASE.reset_index().rename(columns={'VIGA':'FD_3'})
        fd_04_initial = self.FCF_BASE.reset_index().rename(columns={'VDFA':'FD_4'})
        # | REG_exp | REG_imp | TRAD_COMM |

        fd_initial = fd_01_initial.merge(fd_03_initial, how="outer").merge(fd_04_initial, how="outer")
        fd_initial = pd.melt(fd_initial, id_vars=['REG_exp','REG_imp','TRAD_COMM'],
                              var_name='PROD_COMM', value_name='y0')
        fd_initial['y0'] = fd_initial['y0'].fillna(0)
        del fd_01_initial, fd_03_initial, fd_04_initial
        # | REG_imp | REG_exp | TRAD_COMM | PROD_COMM [FD_1-FD_4] | y0 #

        fd_initial = fd_initial.astype({'TRAD_COMM':'str'})
        fd_exog = fd_exog.merge(fd_initial, how='left', on=['REG_imp','REG_exp','TRAD_COMM','PROD_COMM'])
        fd_exog['dy'] = 0.0

        # assigned vars dict
        variables = {}
        # ? assign
        df_assign = fd_exog[fd_exog['Type'].str.contains('assign')].copy()

        for i, r in df_assign.iterrows():
            name = r['Value'].replace("[TRAD_COMM]",str(r['TRAD_COMM'])).replace("[REG_imp]",str(r['REG_imp'])).replace("[REG_exp]",str(r['REG_exp'])).replace("[PROD_COMM]",str(r['PROD_COMM']))
            match_ = (df_assign['REG_imp']==r['REG_imp']) & (df_assign['TRAD_COMM']==r['TRAD_COMM']) & (df_assign['PROD_COMM']==r['PROD_COMM']) & (df_assign['REG_exp']==r['REG_exp'])
            variables[name] = variables[name] + df_assign.loc[match_, 'y0'] #type: ignore

        variables_df = pd.DataFrame({"index": variables.keys(), "value": [x.values[0] if len(x)!=0 else 0 for x in variables.values()]})

        # ? eval
        # ? eval can access both variables_df and fd_exog
        df_eval = fd_exog[fd_exog['Type'].str.contains('eval')].copy()

        for i, r in df_eval.iterrows():
            match_ = (df_eval['REG_imp']==r['REG_imp']) & (df_eval['TRAD_COMM']==r['TRAD_COMM']) & (df_assign['PROD_COMM']==r['PROD_COMM']) & (df_assign['REG_exp']==r['REG_exp'])
            exp = r['Value'].replace("[PROD_COMM]",str(r['PROD_COMM'])).replace("[TRAD_COMM]",str(r['TRAD_COMM'])).replace("[REG_imp]",str(r['REG_imp'])).replace("[REG_exp]",str(r['REG_exp']))
            df_eval.loc[match_, 'dy'] = eval(exp)

        # ? abs-b: abs-b is absolute impact based on Y0
        # ? if multiple specified from something, then spread out proportionally

        df_absb = fd_exog[fd_exog['Type'].str.contains('abs-b')].copy()
        # calculate share by line
        df_absb['share'] = df_absb['y0'] / df_absb.groupby(['Line'])['y0'].transform('sum')
        df_absb['dy'] = df_absb['Value'] * df_absb['share']
        # ? rel-b

        df_relb = fd_exog[fd_exog['Type'].str.contains('rel-b')].copy()
        df_relb['dy'] = df_relb['y0'] * df_relb['Value']

        # ! LINES either overwrite each other (last one stays) or appended (sum)
        # ! only SUM for now!

        df_impacts = pd.concat([df_eval, df_absb, df_relb])
        self.Log.log_to_csv("fd_exog_", df_impacts)
        # ? REG_imp | REG_exp | TRAD_COMM | PROD_COMM [FD_1] | dy
        df_impacts = df_impacts.drop(columns=['Value','y0','Line'])
        df_impacts = df_impacts.groupby(['REG_exp','REG_imp','TRAD_COMM','PROD_COMM']).agg({'dy':'sum'}).reset_index()
        self.fd_exog = df_impacts

        return True

    # ^ //////////////////////////////////////
    
    # ^ ------------------------------------
    # ^   Sheet: Investment BY sector       
    # ^ ------------------------------------

    def set_exog_inv(self):
        # columns to be passed on
        columns_ = ['REG_imp','PROD_COMM','Value','Type']

        try:
            inv_exog = pd.read_excel(self.scenario_file, sheet_name='Investment by')
            inv_exog = inv_exog[['Country ISO*','Sector investing code*','Value*','Type*']]
            inv_exog.columns = columns_
        except ValueError:
            inv_exog = pd.DataFrame(columns=columns_)


        # read in power investment, if any
        try:
            power_inv_exog = pd.read_excel(self.scenario_file, sheet_name='Power investment')
            power_inv_exog = power_inv_exog[['Country ISO*','Investing sector code*','Value*','Type*']]
            power_inv_exog.columns = columns_
        except ValueError:
            power_inv_exog = pd.DataFrame(columns=columns_)

        inv_exog = pd.concat([inv_exog, power_inv_exog], axis=0)     

        # add index before resolving
        inv_exog['Line'] = np.arange(len(inv_exog)).tolist()

        inv_exog = resolve_comma(inv_exog, "REG_imp")
        inv_exog = resolve_all(inv_exog, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        inv_exog = resolve_comma(inv_exog, "PROD_COMM")
        inv_exog = resolve_hyphen(inv_exog, "PROD_COMM")
        inv_exog = resolve_all(inv_exog, "PROD_COMM", [x for x in np.arange(1,121)])

        # ? Scenario.fd_exog structure is the following:
        # ? REG_imp | PROD_COMM | Value | Type
        # ? Type can be: abs-b [absolute-proportional-base] | abs [absolute-proportional-new] 
        # ? | rel [relative] | rel-b [relative to baseline]
        # ? if absolute is used with multiple sectors / countries
        # ? then numbers are proportionally spread out
        # ? proportionality is either to the base [abs-b] or to the current FD vector [abs]
        # TODO: abs is to be implemented later [with annualized model version]
        # TODO: rel is to be implemented later [with annualized model version]
        # TODO: rel-b is to be implemented later !! - we don't have investment baseline BY 
        # TODO: investing sector

        # ? abs-b: abs-b is absolute impact based on Y0
        # ? if multiple specified from something, then spread out proportionally

        df_absb = inv_exog[inv_exog['Type'].str.contains('abs-b')].copy()
        # calculate share by line
        df_absb['dk'] = df_absb['Value']

        # ! LINES either overwrite each other (last one stays) or appended (sum)
        # ! only SUM for now!

        df_impacts = pd.concat([df_absb])
        self.Log.log_to_csv("inv_exog_", df_impacts)
        # ? REG_imp | PROD_COMM | dk
        df_impacts = df_impacts.drop(columns=['Value','Line'])
        df_impacts = df_impacts.groupby(['REG_imp','PROD_COMM']).agg({'dk':'sum'}).reset_index()

        self.inv_exog = df_impacts

        return True
    
    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Power investment     
    # ^ -----------------------------------------------
    def set_ely_investment(self):
        # columns to be passed on
        columns_ = ['REG_imp', 'Region', 'PROD_COMM','Renewables','Value']
        columns_empty =  ['REG_imp','PROD_COMM','TRAD_COMM','Value', 'Type']
        try:
            power_inv = pd.read_excel(self.scenario_file, sheet_name='Power investment', skiprows=14)
            power_inv = power_inv[['Country ISO*','Region*','Investing sector code*','Renewables*','Value*']]
            power_inv.columns = columns_
        except ValueError:
            power_inv = pd.DataFrame(columns=columns_empty)
        
        if(len(power_inv)>1):
            # sum across renewables and calculate shares
            # power_share = pd.read_excel(self.scenario_file, sheet_name='Power_investment', skiprows=14)
            shares = power_inv.groupby(['REG_imp', 'Region', 'PROD_COMM','Renewables'], as_index=False).sum()
            shares['share'] = shares['Value']/(shares['Value'].sum())
            shares = shares[shares['share'] != 0]
            
            # Read in renewable investment converters
            region = power_inv['Region'].drop_duplicates().items()
            region="ROW"
            inv_renew=pd.read_excel(os.getcwd() + '\\GLORIA_template\\Investment\\Inv_renewables.xlsx',
                                  sheet_name=region, skiprows=1)
            # inv_renew = inv_renew.iloc[:,1:]
            inv_renew_long = pd.melt(inv_renew, id_vars=['ID', 'Sector'], 
                                          var_name='Renewables', 
                                          value_name='value')
            
            # Merge shares and investment converter
            merge_df = inv_renew_long.merge(shares,on=['Renewables'])
            merge_df['new_share'] = merge_df['value'] * merge_df['share'] 
            new_share = merge_df.groupby(['ID','REG_imp','PROD_COMM'], as_index=False).sum()
            new_share = new_share[['REG_imp', 'PROD_COMM', 'ID', 'new_share']]
            new_share.rename(columns={'ID':'TRAD_COMM', "new_share":"Value"}, inplace=True)
            new_share = new_share[new_share['Value'] != 0.0]
            # set type to replace
            new_share['Type'] = 'replace'
            
        else:
            new_share = power_inv

        return new_share
    
    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Investment converter adjustment       
    # ^ -----------------------------------------------

    def set_inv_conv_adj(self, exog_vars:exog_vars):
        # columns to be passed on
        columns_ = ['REG_imp','PROD_COMM','TRAD_COMM','Value','Type']

        try:
            inv_conv_adj = pd.read_excel(self.scenario_file, sheet_name='Investment converter', skiprows=14)
            inv_conv_adj = inv_conv_adj[['Country ISO*','Investing sector code*','Investment good sector code*','Value*','Type*']]
            inv_conv_adj.columns = columns_
        except ValueError:
            inv_conv_adj = pd.DataFrame(columns=columns_)
                        
        # Merge with power_investment shares
        inv_conv_adj = pd.concat([inv_conv_adj, self.set_ely_investment()], axis=0)
        
        # generate full matrix
        inv_conv = exog_vars.INV_CONV #type:ignore 
        inv_conv.columns = ['TRAD_COMM'] + inv_conv.columns[1:].tolist()
        inv_conv = pd.melt(inv_conv, id_vars=['TRAD_COMM'], var_name='PROD_COMM', value_name='input_coeff')
        df_inv_conv = inv_conv[inv_conv['input_coeff']!=0.0].copy()
        a1 = len(df_inv_conv)

        df_inv_conv = pd.concat([df_inv_conv for x in range(len(self.REGIONS))])
        df_inv_conv['REG_imp'] = np.repeat(self.REGIONS['Region_acronyms'], a1).tolist()

        if len(inv_conv_adj) > 0:

            inv_conv_adj = resolve_comma(inv_conv_adj, "REG_imp")
            inv_conv_adj = resolve_all(inv_conv_adj, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

            inv_conv_adj = resolve_comma(inv_conv_adj, "PROD_COMM")
            inv_conv_adj = resolve_hyphen(inv_conv_adj, "PROD_COMM")
            inv_conv_adj = resolve_all(inv_conv_adj, "PROD_COMM", [x for x in np.arange(1,121)])

            inv_conv_adj = resolve_comma(inv_conv_adj, "TRAD_COMM")
            inv_conv_adj = resolve_hyphen(inv_conv_adj, "TRAD_COMM")
            inv_conv_adj = resolve_all(inv_conv_adj, "TRAD_COMM", [x for x in np.arange(1,121)])

            # ? Type can be:
            # ? abs-b | rel-b | abs | rel | replace
            # TODO: abs is to be implemented later
            # TODO: abs is to be implemented later
            # TODO: abs-b is to be implemented later [with annualized model version]
            # TODO: rel-b is to be implemented later [with annualized model version]

            # ! NOTE: with this setup there is no differentiation in terms of investment conversion
            # ! between INDUCED | RECYCLED | EXOG investment types
            # TODO: might need to change this

            # ? replace: replace is direct replacement of INV_CONV coeffs

            df_replace = inv_conv_adj[inv_conv_adj['Type'].str.contains('replace')].copy()
            # calculate 
            df_inv_conv = df_inv_conv.astype({'TRAD_COMM':'str'})
            df_inv_conv = df_inv_conv.merge(df_replace, how='outer', on=['REG_imp','PROD_COMM','TRAD_COMM'])
            df_inv_conv.loc[~df_inv_conv['Value'].isna(),'input_coeff'] = df_inv_conv['Value']

            # ! ALWAYS rebalancing to 1 [column-wise | PROD_COMM]
            df_inv_conv['new_input_coeff'] = df_inv_conv['input_coeff'] * (1 / df_inv_conv.groupby(['REG_imp','PROD_COMM'])['input_coeff'].transform('sum'))
            df_inv_conv = df_inv_conv.fillna(0)
            self.Log.log_to_csv("inv_converter_adj_", df_inv_conv)
            df_inv_conv['input_coeff'] = df_inv_conv['new_input_coeff']

            df_inv_conv = df_inv_conv.drop(columns=['Type','Value','new_input_coeff'])
        
        return df_inv_conv

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Price change (tax or non-tax)         
    # ^ -----------------------------------------------

    def set_cost_shock(self):
        try:
            cost_shock = pd.read_excel(self.scenario_file, sheet_name="Price change", skiprows=14)
            cost_shock = cost_shock[['Origin country ISO*','Target country ISO*','Origin sector code*',
                                     'Target sector code*','Value*','Type*']]
            cost_shock.columns = ['REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type']
        except ValueError:
            cost_shock = pd.DataFrame(columns=['REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type'])

        # add LINE id
        cost_shock['line'] = range(len(cost_shock))

        cost_shock = resolve_comma(cost_shock, "REG_imp")
        cost_shock = resolve_all(cost_shock, "REG_imp", self.REGIONS['Region_acronyms'].to_list())

        cost_shock = resolve_comma(cost_shock, "REG_exp")
        cost_shock = resolve_all(cost_shock, "REG_exp", self.REGIONS['Region_acronyms'].to_list())

        cost_shock = resolve_comma(cost_shock, "PROD_COMM")
        cost_shock = resolve_hyphen(cost_shock, "PROD_COMM")
        cost_shock = resolve_all(cost_shock, "PROD_COMM", [x for x in np.arange(1,121)])

        cost_shock = resolve_comma(cost_shock, "TRAD_COMM")
        cost_shock = resolve_hyphen(cost_shock, "TRAD_COMM")
        cost_shock = resolve_all(cost_shock, "TRAD_COMM", [x for x in np.arange(1,121)])

        # price changes are captured on the level of production sector, not 

        # ? two types of cost shock
        # ? tax-abs -> used for e.g., FFSR, picked up by Ener_model.assign_price_change
        # ? increases tax-rate and therefore generates tax revenues; assigned using output share of impacted sectors
        # ! For carbon taxing use the carbon tax module!!

        # ? rel -> used for non-tax type cost shocks, picked up by Prod_cost.prod_cost_impact
        # ? increases production cost of the good therefore reducing demand

        self.cost_shock = cost_shock

    # ^ //////////////////////////////////////

    # ^ -----------------------------------------------
    # ^   Sheet: Supply constraints                    
    # ^ -----------------------------------------------


    def set_supply_constraint(self):
        try:
            supply_constraint = pd.read_excel(self.scenario_file, sheet_name="Supply constraint", skiprows=14)
            supply_constraint = supply_constraint[['Country ISO*','Product code*','Value*','Type*']]
            supply_constraint.columns = ['REG_imp','PROD_COMM','Value','Type']
        except ValueError:
            supply_constraint = pd.DataFrame(columns=['REG_imp','PROD_COMM','Value','Type'])

        supply_constraint['line'] = np.arange(len(supply_constraint)).tolist()

        supply_constraint = resolve_comma(supply_constraint, 'REG_imp')
        supply_constraint = resolve_all(supply_constraint, 'REG_imp', self.REGIONS['Region_acronyms'].to_list())

        supply_constraint = resolve_comma(supply_constraint, 'PROD_COMM')
        supply_constraint = resolve_hyphen(supply_constraint, 'PROD_COMM')
        supply_constraint = resolve_all(supply_constraint, 'PROD_COMM', [x for x in np.arange(1,121)])
        
        supply_constraint = supply_constraint.drop(columns=['line'])
        supply_constraint = supply_constraint.groupby(['REG_imp','PROD_COMM','Type']).agg({'Value':'sum'}).reset_index()
        
        self.supply_constraint = supply_constraint

    # ^ //////////////////////////////////////
    
    def set_io_changes(self):
        try:
            io_changes = pd.read_excel(self.scenario_file, sheet_name="Input-output coefficients", skiprows=14)
            io_changes = io_changes[['Origin country ISO*','Target country ISO*','Origin sector code*','Target sector code*','Value*','Type*']]
            io_changes.columns = ['REG_exp','REG_imp','TRAD_COMM','PROD_COMM','Value','Type']
            
            # index
            io_changes['line'] = range(len(io_changes))
            # resolve hyphen
            io_changes = resolve_hyphen(io_changes, 'TRAD_COMM')
            io_changes = resolve_hyphen(io_changes, 'PROD_COMM')
            io_changes = resolve_all(io_changes, 'TRAD_COMM', [x for x in np.arange(1,121)])
            io_changes = resolve_all(io_changes, 'PROD_COMM', [x for x in np.arange(1,121)])
            
            # Save inputs for Specific country
            io_changes_specific = io_changes[(io_changes['REG_exp']!='ALL') & (io_changes['REG_imp']!='ALL')].copy()
            # treatment of ALL in REG_exp
            pairs = io_changes[io_changes['REG_exp']=='ALL'][['REG_imp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_exp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
                    
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
                io_changes = pd.concat([io_changes[io_changes['REG_exp']!='ALL'], complement_ALL])
                
                del complement_ALL
            # treatment of ALL in REG_imp
            pairs = io_changes[io_changes['REG_imp']=='ALL'][['REG_exp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_imp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
    
                io_changes = pd.concat([io_changes[io_changes['REG_imp']!='ALL'], complement_ALL])
    
                del complement_ALL
                    
            # treatment of KEEP in REG_exp
               # total of input needs to be as specified, but keep distribution across REG_exp
            pairs = io_changes[io_changes['REG_exp']=='KEEP'][['REG_imp','PROD_COMM','TRAD_COMM','Value','Type','line']].copy()
            if len(pairs) > 0:
                # TODO: for now this is okay, but if we have more lines of scenario this might gonna cause issues
                pairs['key'] = 1
                keys = pd.DataFrame({
                    'REG_exp': self.REGIONS['Region_acronyms'].to_list(),
                    'key': 1
                })
    
                complement_ALL = keys.merge(pairs, how='left', on='key').drop(columns=['key'])
                # now we need to recalculate the relevant shares
                # complement_ALL is
                # REG_exp, REG_imp, PROD_COMM, TRAD_COMM, Value'
                complement_ALL = (complement_ALL.astype({'TRAD_COMM':'int','PROD_COMM':'int'})).merge(self.IND_BASE[['REG_imp','REG_exp','PROD_COMM','TRAD_COMM','z_bp']], 
                                     how='left', on=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM'])
                # calculate relevant share
                complement_ALL['REG_exp_share'] = \
                    complement_ALL['z_bp'] / complement_ALL.groupby(['REG_imp','PROD_COMM','TRAD_COMM'])['z_bp'].transform('sum')
                complement_ALL['Value'] = complement_ALL['Value'] * complement_ALL['REG_exp_share']
                complement_ALL = complement_ALL.drop(columns=['z_bp','REG_exp_share'])
                io_changes = pd.concat([io_changes[io_changes['REG_exp']!='KEEP'], complement_ALL])
                del complement_ALL
                
            # we might end up with duplicates, the latest assignment is the valid 
            io_changes = io_changes.sort_values(by='line').drop_duplicates(keep='last', subset=['REG_imp','REG_exp','PROD_COMM','TRAD_COMM']).drop(columns=['line'])

        except ValueError:
            io_changes = pd.DataFrame(columns=['REG_imp','PROD_COMM','REG_exp','TRAD_COMM','Type','Value'])
            
        self.io_changes = io_changes

        return io_changes

    def build_rev_split(self):
        # load tax revenue split
        rev_split = self.scenario_data["rev_split"]
        rev_split.reset_dimensions() # type: ignore
        rev_split = pd.DataFrame(rev_split.values) # type: ignore
        rev_split.columns = rev_split.iloc[0]
        rev_split = rev_split.drop(index=0)
        rev_split = rev_split.reset_index().drop(columns=["index"])
        
        for i in range(1,len(rev_split.columns)):
            colname = rev_split.columns[i]
            rev_split[colname] = pd.Series(rev_split[colname], dtype=float)

        self.rev_split = rev_split

        return self.rev_split

    def build_payr_tax_split(self):
        # load payroll tax split
        payr_tax_split = self.scenario_data["payr_tax_split"]
        payr_tax_split.reset_dimensions() # type: ignore
        payr_tax_split = pd.DataFrame(payr_tax_split.values) # type: ignore
        payr_tax_split.columns = payr_tax_split.iloc[0]
        payr_tax_split = payr_tax_split.drop(index=0)
        payr_tax_split = payr_tax_split.reset_index().drop(columns=["index"])
        # payr_tax_split = pd.read_excel(scenariofile, "payr_tax_split")
        # payr_tax_split["REG_imp"] = payr_tax_split["REG_imp"].str.lower()

        for i in range(1,len(payr_tax_split.columns)):
            colname = payr_tax_split.columns[i]
            payr_tax_split[colname] = pd.Series(payr_tax_split[colname], dtype=float)

        self.payr_tax_split = payr_tax_split

        return self.payr_tax_split

    def build_rev_proportion(self):
        # load proportional allocation
        rev_proportion = self.scenario_data["rev_proportional"]
        rev_proportion.reset_dimensions() # type: ignore
        rev_proportion = pd.DataFrame(rev_proportion.values) # type: ignore
        rev_proportion.columns = rev_proportion.iloc[0]
        rev_proportion = rev_proportion.drop(index=0)
        rev_proportion = rev_proportion.reset_index().drop(columns=["index"])
        # rev_proportion = pd.read_excel(scenariofile, "rev_proportional")

        for i in range(1,len(rev_proportion.columns)):
            colname = rev_proportion.columns[i]
            rev_proportion[colname] = pd.Series(rev_proportion[colname], dtype=float)

        self.rev_proportion = rev_proportion

        return self.rev_proportion
    
    def build_govt_spending(self):
        govt_spending = self.scenario_data["govt_spending"]
        govt_spending.reset_dimensions() # type: ignore
        govt_spending = pd.DataFrame(govt_spending.values) # type: ignore

        govt_spending.columns = govt_spending.iloc[0]
        govt_spending = govt_spending.drop(index=0)
        govt_spending = govt_spending.reset_index().drop(columns=["index"])
        govt_spending = govt_spending.rename(columns={"REG":"REG_imp", "PROD_COMM":"TRAD_COMM"})
        govt_spending["govt_spend"] = pd.Series(govt_spending["govt_spend"], dtype=float)
        
        self.govt_spending = govt_spending

        return self.govt_spending
    
    def build_inv_spending(self):
        inv_spending = self.scenario_data["inv_spending"]
        inv_spending.reset_dimensions() # type: ignore
        inv_spending = pd.DataFrame(inv_spending.values) # type: ignore

        inv_spending.columns = inv_spending.iloc[0]
        inv_spending = inv_spending.drop(index=0)
        inv_spending = inv_spending.reset_index().drop(columns=["index"])
        inv_spending = inv_spending.rename(columns={"REG":"REG_imp"})
        inv_spending["PROD_COMM"] = pd.Series(inv_spending["PROD_COMM"], dtype=int)
        inv_spending["inv_spend"] = pd.Series(inv_spending["inv_spend"], dtype=float)

        self.inv_spending = inv_spending

        return self.inv_spending
    
    def assign_bta(self, bta):
        self.bta = bta
    
    
